### hello
GET {{baseUrl}}/v1/keys
Accept: application/json

### get certs
GET {{baseUrl}}/v1/keys/updates?since={{since}}&certFormat={{certFormat}}
Accept: application/json
Authorization: Bearer {{apiKey}}

### get active cert key ids
GET {{baseUrl}}/v1/keys/list
Accept: application/json
ETag: -720957702
Authorization: Bearer {{apiKey}}

### get revocation list
GET {{baseUrl}}/v1/revocationList
Accept: application/json
ETag: -103666649
Authorization: Bearer {{apiKey}}

### get verification rules
GET {{baseUrl}}/v1/verificationRules
Accept: application/json
ETag: f4915f1428328eb6c239693fc8e6541f68a3f72e
Authorization: Bearer {{apiKey}}

### get verification rules
GET {{baseUrl}}/v1/valueSets
Accept: application/json
ETag: f4915f1428328eb6c239693fc8e6541f68a3f72e
Authorization: Bearer {{apiKey}}