### hello
GET {{syncBaseUrl}}/dgcHub
Accept: application/json

### proxy
GET {{syncBaseUrl}}/dgcHub/proxy?endpoint=valuesets/covid-19-lab-result
Accept: application/json

### upload dsc aliases
GET {{syncBaseUrl}}/dsc/upload/trigger
Accept: application/json