# This workflow will build a Java project with Maven when a tag is pushed
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
---
name: Java CI with Maven
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11.0.7
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file: :
    - name: Build with Maven
      run: |
        mvn clean install --file ch-covidcertificate-backend-verifier/pom.xml;
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TESTCONTAINERS_RYUK_DISABLED: true
    - name: shasum
      run: shasum -a 256 ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-sync/target/ch-covidcertificate-backend-verifier-sync.jar > ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-sync/target/ch-covidcertificate-backend-verifier-sync.jar.sha256
      shell: bash
    - name: shasum
      run: shasum -a 256 ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-ws/target/ch-covidcertificate-backend-verifier-ws.jar > ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-ws/target/ch-covidcertificate-backend-verifier-ws.jar.sha256
      shell: bash
    - name: "Create new release"
      uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: ${{ contains(github.ref, 'prerelease') }}
        files: |
          ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-sync/target/ch-covidcertificate-backend-verifier-sync.jar
          ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-sync/target/ch-covidcertificate-backend-verifier-sync.jar.sha256
          ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-ws/target/ch-covidcertificate-backend-verifier-ws.jar
          ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-ws/target/ch-covidcertificate-backend-verifier-ws.jar.sha256
          ch-covidcertificate-backend-verifier/ch-covidcertificate-backend-verifier-ws/openapi.yaml
